language: r
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

before_install:
  - sh -e /etc/init.d/xvfb start

after_success:
  - Rscript -e 'covr::coveralls()'

r_build_args: "--resave-data=best"
r_check_args: "--as-cran"

env:
   global:
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1
